### PR TITLE
Guard for in loops

### PR DESCRIPTION
**Pull request by alechirsch**
I am using this package in an ember application and it is causing some errors where prototype functions are placed inside the arrays.

### CODE REVIEW

**Comment by matteo-harpoon** [comment]
@alechirsch Yes it all makes sense! I apologise for the errors, I'll merge your commit right away!

**Comment by alechirsch** [comment]
Thanks for merging, can you let me know when this is published?

**Comment by matteo-harpoon** [comment]
@alechirsch I believe it's already pushed

**Comment by alechirsch** [comment]
@matteo-harpoon On NPM it says published 6 months ago

**Comment by matteo-harpoon** [comment]
You're right! I'll push to NPM in a min.

**Comment by matteo-harpoon** [comment]
@alechirsch I've published to NPM and pushed to Git. I apologise for the delay.

**Pull request merged**
